# Generated by Django 4.2.1 on 2023-05-19 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querygenerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('functionality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querygenerator.functionality')),
            ],
        ),
    ]
