# Generated by Django 4.2.1 on 2023-05-19 02:56

from django.db import migrations


def initialize_functionalities(apps, schema_editor):
    Functionality = apps.get_model('querygenerator', 'Functionality')
    Functionality.objects.bulk_create([
        Functionality(name='generate'),
        Functionality(name='explain_sql'),
        Functionality(name='fix_query'),
        Functionality(name='suggest_optimization'),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('querygenerator', '0002_useractivity'),
    ]

    operations = [
        migrations.RunPython(initialize_functionalities),
    ]
